apiVersion: v1
data:
  config.yaml: |
    alertmanagerMain: null
    enableUserWorkload: true
    http: null
    k8sPrometheusAdapter: null
    kubeStateMetrics: null
    openshiftStateMetrics: null
    prometheusK8s:
      additionalAlertmanagerConfigs:
      - apiVersion: v2
        bearerToken:
          key: token
          name: observability-alertmanager-accessor
        pathPrefix: /
        scheme: https
        staticConfigs:
        - {{hub (lookup "route.openshift.io/v1" "Route" "openshift-monitoring" "alertmanager-main").spec.host | replace "-main-openshift-monitoring" "-open-cluster-management-observability" hub}}
        tlsConfig:
          ca:
            key: service-ca.crt
            name: hub-alertmanager-router-ca
          insecureSkipVerify: false
      externalLabels:
        {{- $clusterID := (lookup "config.openshift.io/v1" "ClusterVersion" "" "version").spec.clusterID }}
        cluster: '{{ $clusterID }}'
        managed_cluster: '{{ $clusterID }}'
      logLevel: ""
      nodeSelector: null
      queryLogFile: ""
      remoteWrite: null
      resources: null
      retention: 15d
      retentionSize: 40GB
      tolerations: null
      volumeClaimTemplate: null
    prometheusOperator: null
    telemeterClient: null
    thanosQuerier: null
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
