---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: policygen-monitoring
  namespace: policy-generator
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - policygen-monitoring
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: low
  name: policygen-monitoring-channel
  namespace: policy-generator
spec:
  type: Git
  pathname: 'https://github.com/SerenaFlocco/test-policy-generator.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: /
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policygen-monitoring
  name: policygen-monitoring-subscription
  namespace: policy-generator
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - Placement
  channel: policy-generator/policygen-monitoring-channel
  placement:
    placementRef:
      kind: Placement
      name: policygen-monitoring-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: Placement
metadata:
  labels:
    app: policygen-monitoring
  name: policygen-monitoring-placement
  namespace: policy-generator
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - key: local-cluster
            operator: In
            values:
              - "true"
