apiVersion: v1
data:
  config.yaml: |
    prometheus:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "node-role.kubernetes.io/infra-metrics"
        operator: Exists
        effect: "NoExecute"
      resources:
        requests:
          cpu: 200m
          memory: 2Gi
    thanosRuler:
      resources:
        requests:
          cpu: 20m
          memory: 50Mi
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: "node-role.kubernetes.io/infra-metrics"
        operator: Exists
        effect: "NoExecute"
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
